#INSERT DOS TIPOS DE PERFIS DA FESTA
INSERT INTO TB_PERFIL VALUES
	(1, 'CONVIDADO'),
	(2, 'FUNCIONÁRIO'),
	(3, 'DETETIVE'),
	(4, 'OFICIAIL');
 
#INSERT DAS ESPECIES DO REINO
INSERT INTO TB_ESPECIE VALUES
    (1, 'ONÇA-PINTADA'),
    (2, 'ARARA-AZUL'),
    (3, 'TAMANDUÁ-BANDEIRA'),
    (4, 'TUCANO'),
    (5, 'JAGUATIRICA'),
    (6, 'MICO-LEÃO-DOURADO'),
    (7, 'ANTA'),
    (8, 'PAPAGAIO-VERDADEIRO'),
    (9, 'PIRANHA'),
    (10, 'JABUTI'),
    (11, 'CAPIVARA'),
    (12, 'SAGUI'),
    (13, 'TAMANDUÁ-MIRIM'),
    (14, 'SUÇUARANA'),
    (15, 'JACARÉ-AÇU'),
    (16, 'BOTO-COR-DE-ROSA'),
    (17, 'TATU-CANASTRA'),
    (18, 'GAVIÃO-REAL'),
    (19, 'VEADO-CATINGUEIRO'),
    (20, 'TATU-BOLA'),
    (21, 'SAPO-CURURU'),
    (22, 'MICO-ESTRELA'),
    (23, 'COBRA-CORAL'),
    (24, 'LOBO-GUARÁ'),
    (25, 'PAVÃOZINHO-DO-PARÁ'),
    (26, 'BICHO-PREGUIÇA'),
    (27, 'CACHORRO-VINAGRE'),
    (28, 'PEIXE-BOI'),
    (29, 'CARCARÁ'),
    (30, 'SABIÁ-LARANJEIRA'),
    (31, 'HARPIA'),
    (32, 'RATO-DO-MATO'),
    (33, 'PIRARUCU'),
	(34, 'TOURO'),
    (35, 'PANDA'), #ANDRÉ
    (36, 'PORQUINHO DA INDIA'),#DUDU
    (37, 'FOCA'),#ALFAYA
    (38, 'COALA'),#RODRIGO
    (39, 'CORUJA');#JOHN
    
#INSERT DE MAGIAS
INSERT INTO TB_MAGIA VALUES
	(1, 'AR'),
    (2, 'ÁGUA'),
    (3, 'TERRA'),
    (4, 'FOGO'),
    (5, 'TREVAS'),
    (6, 'FLORESTA'),
    (7, 'LUZ'),
    (8, 'ALQUIMÍA'),
    (9, 'GELO');
    
#INSERT DOS TITULOS DE NOBRESA
INSERT INTO TB_TITULO VALUES
	(1, 'BARÃO'),
    (2, 'VISCONDE'),
    (3, 'FAMÍLIA REAL'),
    (4, 'DUQUE'),
    (5, 'MARQUÊS'),
    (6, 'CONDE'),
    (7, 'BARONETE'),
    (8, 'CAVALEIRO'),
    (9, 'EMBAIXADORA'),
	(10, 'NENHUM');
    
INSERT INTO TB_REGIAO VALUES
	(1, 'NORTE'),
    (2, 'SUL'),
    (3, 'LESTE'),
    (4, 'OESTE'),
    (5, 'CENTRO');
    
INSERT INTO TB_AFILIACAO VALUES
	(1, 'PIRATAS SUL'), ## ATENÇÃO
    (2, 'ALQUIMISTAS DO OESTE'),
    (3, 'SEGUIDORES DE SERPENTIUM'), #LESTE
    (4, 'REINO DE PANDORA'), #CENTRO
	(5, 'PROTETORES DE AMASSUNU'), #NORTE
	(6, 'ANDARILHOS DO NORTE'),
    (7, 'SOCIEDADE SECRETA'),
	(8, 'NENHUMA');

#ID, NOME, CAF, DATA, AFILIACAO, ESPECIE, TITULO, MAGIA, REGIAO, PERFIL
INSERT INTO TB_PERSONAGEM VALUES
	(1, 'ISABEL MONTENEGRO', '49276912933', '1953-12-09', 1, 1, 9, 9, 2, 1),
    (2, 'MÁRCIO RENE BRANDÃO SOUSSA', '98164621632', '1965-07-11', 6, 31, 6, 1, 5, 1),
	(3, 'THOMAS JERRY', '13984141544', '1996-08-21', 5, 32, 10, 6, 1, 1),
	(4, 'FERDINANDO GONZÁLEZ', '74859645859', '1972-05-21', 4, 34, 7, 3, 5, 1),
	(5, 'CHARLES BACON', '95753813137', '1995-11-30', 6, 27, 10, 2, 1, 2),
	(6, 'IRACEBETH QUEEN', '65132984653', '1956-02-19', 4, 23, 3, 9, 5, 1),
	(7, 'ARSENE LUPIN', '68348465112', '1980-09-09', 3, 15, 1, 7, 3, 1),
	(8, 'ROBERTO D. XAVIER', '54127896156', '1950-03-14', 1, 18, 4, 7, 2, 1),
    (9, 'EDUARDO FISCINA MENEZES MORAES', '14568974563', '2002-09-01', 2, 36, 10, 4, 2, 2),
    (10, 'JOHN VITOR NUNES DE CARVALHO', '963852456459','2002-10-08', 7, 39, 10, 5, 1, 1),
    (11, 'ANDRE LUCAS DO NASCIMENTO DOS SANTOS', '36521986457', '2003-02-06', 7, 35, 10, 3, 3, 3),
    (12, 'IAGO SANTANA ALFAYA', '85245696341','2002-05-10', 7, 37, 10, 9, 4, 2),
    (13, 'RODRIGO DE JESUS MACEDO', '556321576849', '1999-07-12', 7, 38, 10, 6, 5, 2),
    (14, 'CLEBER ARADO MONTEZ', '85245693178', '1970-05-20', 4, 24, 5, 5, 3, 1);

#INSERT DOS NOMES DAS SALAS
INSERT INTO TB_SALA VALUES
    (1, 'HALL DE ENTRADA', 20),
    (2, 'SALA DE ESTAR', 25),
    (3, 'SALA DE JANTAR', 18),
    (4, 'COZINHA', 10),
    (5, 'ESCRITÓRIO', 8),
    (6, 'BIBLIOTECA', 30),
    (7, 'SALA DE MÚSICA', 15),
    (8, 'SALA DE JOGOS', 20),
    (9, 'SALÃO DE FESTAS', 100),
    (10, 'QUARTO PRINCIPAL', 2),
    (11, 'QUARTO DE HÓSPEDES', 4),
    (12, 'BANHEIRO PRINCIPAL', 1),
    (13, 'BANHEIRO DE HÓSPEDES', 1),
    (14, 'SÓTÃO', 10),
    (15, 'JARDIM DE INVERNO', 15),
    (16, 'CAPELA', 50);

#INSERT DOS ITENS DAS SALAS
INSERT INTO TB_ITEM VALUES
    (1, 'TAPETES VOADORES', 1),
    (2, 'ESPELHO DO ESQUECIMENTO', 1),
    (3, 'L MPADA DA ILUSÃO', 1),
    (4, 'SOFÁ DOS SONHOS', 2),
    (5, 'POLTRONAS ENCANTADAS', 2),
    (6, 'TELA DA TRANSFORMAÇÃO', 2),
    (7, 'MESA BANQUETEIRA', 3),
    (8, 'TAÇAS ENVENENADAS', 3),
    (9, 'TALHERES HIPNÓTICOS', 3),
    (10, 'PANELA DE DESEJOS', 4),
    (11, 'FACA DO DESTINO', 4),
    (12, 'FRIGIDEIRA DA PETRIFICAÇÃO', 4),
    (13, 'CANETA DA CRIATIVIDADE', 5),
    (14, 'LIVRO DOS FEITIÇOS PROIBIDOS', 5),
    (15, 'CADEIRA DA DESTRUIÇÃO', 5),
    (16, 'PERGAMINHO DA SABEDORIA', 6),
    (17, 'LIVRO DAS SOMBRAS', 6),
    (18, 'ESTANTE ARMADILHA', 6),
    (19, 'FLAUTA ENCANTADORA', 7),
    (20, 'TROMPETE DO TROVÃO', 7),
    (21, 'BATERIA EXPLOSIVA', 7),
    (22, 'TABULEIRO DA ILUSÃO', 8),
    (23, 'DARDOS ENVENENADOS', 8),
    (24, 'BARALHO MALDITO', 8),
    (25, 'BOLA DE DISCOTECA HIPNÓTICA', 9),
    (26, 'COQUETEL DE VENENO', 9),
    (27, 'FOGOS DE ARTIFÍCIO MÁGICOS', 9),
    (28, 'CAMA DO DESCANSO ETERNO', 10),
    (29, 'ESPELHO DA ILUSÃO MORTAL', 10),
    (30, 'ABAJUR DA ESCURIDÃO', 10),
    (31, 'TRAVESSEIRO DO SONO PROFUNDO', 11),
    (32, 'TAPETE VOADOR ASSASSINO', 11),
    (33, 'RELÓGIO DO TEMPO DESCONTROLADO', 11),
    (34, 'TAPETE DE BANHO AQUECIDO', 12),
    (35, 'SABONETE EXPLOSIVO', 12),
    (36, 'ESCOVA DE DENTES DO AZAR', 12),
    (37, 'TOALHA DE BANHO TRANSFORMADORA', 13),
    (38, 'BANHEIRA DO AFOGAMENTO ILUSÓRIO', 13),
    (39, 'VASO SANITÁRIO EXPLOSIVO', 13),
    (40, 'BAÚ DOS SEGREDOS', 14),
    (41, 'ARANHAS DA MALDIÇÃO', 14),
    (42, 'VASSOURA VOADORA DA DESTRUIÇÃO', 14),
    (43, 'PLANTAS CANTANTES', 15),
    (44, 'ROSA DO SONO PROFUNDO', 15),
    (45, 'ESTÁTUA DO GELO ETERNO', 15),
    (46, 'VELAS DO ENCANTAMENTO', 16),
    (47, 'LIVRO SAGRADO DA CONDENAÇÃO', 16),
    (48, 'ÓRGÃO DAS ALMAS PERDIDAS', 16);

#INSERT DO CASAMENTO NA TABELA CASAMENTO
INSERT INTO TB_EVENTO VALUES
	(1, 'CASAMENTO');

#INSERT DA PROGRAMAÇÃO DO CASAMENTO
INSERT INTO TB_PROGRAMACAO VALUES
    (1, 'PREPARAÇÃO DA NOIVA', 10, 1, '09:00', '11:40'),
    (2, 'PREPARAÇÃO DO NOIVO', 10, 1, '12:00', '12:30'),
    (3, 'ALMOÇO', 3, 1, '13:00', '14:00'),
    (4, 'CERIMÔNIA DE CASAMENTO', 16, 1, '15:00', '16:00'),
    (5, 'SESSÃO DE FOTOS DOS NOIVOS', 15, 1, '16:00', '16:30'),
    (6, 'JANTAR DE CASAMENTO', 3, 1, '16:30', '17:30'),
    (7, 'BRINDE DE CASAMENTO', 3, 1, '17:30', '18:00'),
    (9, 'CORTE DO BOLO', 9, 1, '17:30', '18:00'),
    (10, 'DISCURSO DOS PADRINHOS', 9, 1, '18:00', '18:30'),
    (11, 'PRIMEIRA DANÇA DOS NOIVOS', 9, 1, '18:00', '19:00'),
    (12, 'BANDA', 9, 1, '19:00', '20:00'),
    (13, 'BAILE DE CASAMENTO', 9, 1, '20:00', '21:00'),
    (14, 'LANÇAMENTO DO BUQUÊ', 9, 1, '21:00', '21:30'),
    (15, 'FESTA DE CASAMENTO', 16, 1, '21:30', '00:00'),
    (16, 'ENTREGA DOS PRESENTES', 9, 1, '00:00', '01:30'),
    (17, 'DESPEDIDA DOS NOIVOS', 1, 1, '01:40', '02:30');

INSERT INTO TB_FUNCAO VALUES
	(1, 'MORDOMO'),
	(2, 'CERIMONIALISTA'),
	(3, 'SEGURANÇA'),
	(4, 'FLORISTA'),
	(5, 'ESTILISTA'),
	(6, 'MÚSICO'),
	(7, 'FOTÓGRAFO'),
	(8, 'VIDEÓGRAFO'),
	(9, 'CHEFE DE COZINHA'),
	(10, 'GARÇOM'),
	(11, 'MOTORISTA'),
	(12, 'COORDENADOR DE EVENTOS'),
	(13, 'MAÎTRE'),
	(14, 'BARTENDER'),
	(15, 'CAMAREIRO'),
	(16, 'COPEIRO'),
	(17, 'PADEIRO'),
	(18, 'CHEF DE CONFEITARIA'),
	(19, 'RECEPCIONISTA'),
	(20, 'LIMPEZA');

INSERT INTO TB_CONVITE VALUES
    (1, 1, 10, 1),
    (2, 1, 14, 1),
    (3, 1, 11, 1),
    (4, 1, 4, 1),
    (5, 1, 2, 1);

#ID, EVENTO, PERSONAGEM, FUNCAO
INSERT INTO TB_CONTRATO VALUES
    (1, 1, 9, 11), #DUDU
    (2, 1, 13, 20), #RODRIGO
    (3, 1, 12, 10); #ALFAYA

INSERT INTO TB_PELE VALUES
    (1, 'AMARELO'),#ONÇA, JAGUATIRICA, JABUTI, COBRA-CORAL, PAVÃOZINHO-DO-PARÁ
    (2, 'PRETO'),#ONÇA, TUCANO, JAGUATIRICA,CARCARÁ, JABUTI, TAMANDUÁ-MIRIM, GAVIÃO-REAL, TATU-BOLA, COBRA-CORAL, HARPIA, PIRARUCU, TOURO, PANDA
    (3, 'AZUL'), #ARARA-AZUL
    (4, 'DOURADO'), #MICO-LEÃO-DOURADO
    (5, 'MARROM'),#ANTA,  CAPIVARA, SUÇUARANA, TATU CANASTRA, VEADO-CATINGUEIRO, SAPO-CURURU, LOBO-GUARÁ, PAVÃOZINHO-DO-PARÁ, CACHORRO-VINAGRE, SABIÁ-LARANJEIRA, PORQUIIENHO-DA-INDIA
    (6, 'VERDE'),#PAPAGAIO-VERDADEIRO, JACARÉ-AÇU
    (7, 'CINZA'), #PIRANHA, SAGUI,MICO-ESTRELA, BICHO-PREGUIÇA, PEIXE-BOI, RATO-DO-MATO, FOCA, COALA, CORUJA,
    (8, 'LARANJA'), #PIRANHA
    (9, 'BRANCO'), #TAMANDUÁ-MIRIM, GAVIÃO-REAL, CARCARÁ, HARPIA, PANDA, PORQUINHO DA INDIA
    (10, 'ROSA'), #BOTO COR DE ROSA
    (11, 'VERMELHO'); #COBRA CORA, PAVÃOZINHO-DO-PARÁ

#ID, PERSONAGEM, PELO, OLHOS, ALTURA
INSERT INTO TB_MORFOLOGIA VALUES
    (1, 9, 2, 'VERDE',1 );

INSERT INTO TB_DICA VALUES
    (1, 'LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT.'),
    (2, 'DUIS FINIBUS TURPIS URNA, NON AUCTOR DIAM TEMPOR AT.'),
    (3, 'MAECENAS AC ELEIFEND LEO, VEHICULA TINCIDUNT AUGUE.'),
    (4, 'AENEAN VULPUTATE CONSECTETUR MASSA IN EGESTAS.'),
    (5, 'ETIAM COMMODO ORCI QUIS MOLLIS TRISTIQUE.'),
    (6, 'DUIS IN LACINIA NULLA. INTEGER SED ELEIFEND TURPIS.'),
    (7, 'DONEC UT PELLENTESQUE ENIM. ALIQUAM ERAT VOLUTPAT.'),
    (8, 'MAECENAS NEC MAXIMUS TELLUS, ID VULPUTATE MASSA.'),
    (9, 'NUNC IMPERDIET DOLOR VITAE LUCTUS CONSECTETUR.'),
    (10, 'NULLAM ID MASSA BIBENDUM, ULTRICIES DIAM ET, RHONCUS AUGUE.'),
    (11, 'MAURIS LOREM URNA, DAPIBUS UT FELIS ID, DICTUM EGESTAS MASSA.'),
    (12, 'MAURIS PLACERAT NEC IPSUM NON FAUCIBUS.'),
    (13, 'MAURIS FEUGIAT SAPIEN NON FELIS EGESTAS TEMPUS.'),
    (14, 'IN VEL RHONCUS NISI. NUNC SODALES, IPSUM QUIS ULTRICIES LOBORTIS,'),
    (15, 'TURPIS TELLUS TRISTIQUE FELIS, QUIS ORNARE LACUS TELLUS EGET LEO.'),
    (16, 'IN VOLUTPAT MI VITAE PULVINAR SAGITTIS.'),
    (17, 'IN HAC HABITASSE PLATEA DICTUMST.'),
    (18, 'SED FRINGILLA, ANTE SIT AMET FAUCIBUS FINIBUS, TORTOR ORCI SODALES METUS,'),
    (19, 'QUIS VIVERRA LACUS TELLUS ID TURPIS. NULLAM HENDRERIT LOBORTIS TINCIDUNT.'),
    (20, 'PRAESENT SCELERISQUE TELLUS SIT AMET MAGNA INTERDUM, EGET CONSECTETUR SAPIEN PORTA.'),
    (21, 'CRAS PORTTITOR EGESTAS IPSUM NON MATTIS. NAM VITAE DOLOR HENDRERIT,'),
    (22, 'CURSUS FELIS VITAE, LACINIA IPSUM.'),
    (23, 'VESTIBULUM ANTE IPSUM PRIMIS IN FAUCIBUS ORCI LUCTUS ET ULTRICES POSUERE CUBILIA CURAE;'),
    (24, 'VISHHH... ESSE TÁ DOIDO QUE NEM PEDRA | HARLEY: MAS OLHA, PARECE QUE..., LÁ DO DEPARTAMENTO ENCONTROU ALGO PRÓXIMO AO CORPO'),#HARLEY
    (25, 'SUSPENDISSE AC URNA SED SEM ELEMENTUM VIVERRA PLACERAT IN URNA.'),
    (26, 'SED ELIT AUGUE, EFFICITUR ET CONDIMENTUM EGET, LUCTUS EGET ERAT.'),
    (27, 'AENEAN MALESUADA ACCUMSAN SEM. NULLAM AT NIBH SEMPER,'),
    (28, 'CONDIMENTUM ELIT PELLENTESQUE, LAOREET LIBERO.'),
    (29, 'QUISQUE NON SODALES MI, TEMPUS ORNARE ARCU.'),
    (30, 'IN QUIS CONVALLIS RISUS. IN EUISMOD EROS FINIBUS METUS PELLENTESQUE,'),
    (31, 'NEC GRAVIDA VELIT RHONCUS. ALIQUAM IN TINCIDUNT NULLA, NEC CONSECTETUR ELIT.'),
    (32, 'QUISQUE VEHICULA NON MAURIS ET EUISMOD.'),
    (33, 'SED BLANDIT PELLENTESQUE EST, EGET FERMENTUM LIGULA SOLLICITUDIN EGET.'),
    (34, 'DONEC TRISTIQUE EGESTAS DIAM SIT AMET MALESUADA.'),
    (35, 'PRAESENT VITAE VOLUTPAT PURUS, AT PORTA MAGNA.'),
    (36, 'CRAS VENENATIS LOBORTIS DAPIBUS. MAURIS AT ALIQUAM ORCI.'),
    (37, 'NAM SODALES NISL AT EST FINIBUS PORTA. VIVAMUS SED SOLLICITUDIN TURPIS.'),
    (38, 'NULLA SEMPER LOBORTIS QUAM, QUIS HENDRERIT MASSA FAUCIBUS ALIQUET.'),
    (39, 'CURABITUR VARIUS ARCU IACULIS IPSUM LUCTUS, VEL PULVINAR NUNC SCELERISQUE.'),
    (40, ' MEUS PARÁBENS!!!! VOCÊ CHEGOU AO CHECKPOINT'),##HARLEY
    (41, 'PELLENTESQUE FAUCIBUS, QUAM AT CONDIMENTUM SEMPER, EX METUS CONSEQUAT QUAM,'),
    (42, 'AC LOBORTIS MAGNA MI SIT AMET EROS. VIVAMUS NON NEQUE FEUGIAT,'),
    (43, 'LUCTUS MAURIS IN, FINIBUS NIBH. INTEGER AC BIBENDUM EROS.'),
    (44, 'INTEGER DOLOR DOLOR, PORTA'),
    (45, 'SOLLICITUDIN MOLESTIE AC, SUSCIPIT NON DOLOR.'),
    (46, 'PHASELLUS AUCTOR MOLLIS RISUS, VEL EFFICITUR DOLOR POSUERE A.'),
    (47, 'PROIN ET ERAT UT URNA CONSECTETUR VULPUTATE AC VEL METUS.'),
    (48, 'CRAS EFFICITUR DICTUM IMPERDIET. NULLAM IMPERDIET EX ELIT,'),
    (49, 'EGET ALIQUAM ELIT ACCUMSAN IN.'),
    (50, 'CRAS A ENIM ET IPSUM LACINIA VULPUTATE. MAURIS TINCIDUNT VEL EST NON PLACERAT.'),
    (51, 'SED IMPERDIET DUI AT ANTE ULTRICIES PRETIUM. QUISQUE COMMODO TORTOR A PELLENTESQUE VARIUS.'),
    (52, 'PRAESENT IN LAOREET ERAT. DUIS GRAVIDA VELIT QUIS NEQUE POSUERE HENDRERIT AT A NUNC.'),
    (53, 'PROIN SIT AMET CONSECTETUR NISL. PHASELLUS CONDIMENTUM ALIQUET SEM, SIT AMET ORNARE DIAM SAGITTIS ET.'),
    (54, 'PELLENTESQUE HABITANT MORBI TRISTIQUE SENECTUS ET NETUS ET MALESUADA FAMES AC TURPIS EGESTAS.'),
    (55, 'QUISQUE ID VENENATIS ANTE, A BIBENDUM NISL. SUSPENDISSE VESTIBULUM IN TURPIS EU'),
    (56, 'MAECENAS AC ELEIFEND LEO, VEHICULA TINCIDUNT AUGUE.'),
    (57, 'AENEAN VULPUTATE CONSECTETUR MASSA IN EGESTAS.'),
    (58, 'ETIAM COMMODO ORCI QUIS MOLLIS TRISTIQUE.'),
    (59, 'DUIS IN LACINIA NULLA. INTEGER SED ELEIFEND TURPIS.'),
    (60, 'DONEC UT PELLENTESQUE ENIM. ALIQUAM ERAT VOLUTPAT.'),
    (61, 'MAECENAS NEC MAXIMUS TELLUS, ID VULPUTATE MASSA.'),
    (62, 'NUNC IMPERDIET DOLOR VITAE LUCTUS CONSECTETUR.'),
    (63, 'NULLAM ID MASSA BIBENDUM, ULTRICIES DIAM ET, RHONCUS AUGUE.'),
    (64, 'MAURIS LOREM URNA, DAPIBUS UT FELIS ID, DICTUM EGESTAS MASSA.'),
    (65, 'MAURIS PLACERAT NEC IPSUM NON FAUCIBUS.'),
    (66, 'MAURIS FEUGIAT SAPIEN NON FELIS EGESTAS TEMPUS.'),
    (67, 'IN VEL RHONCUS NISI. NUNC SODALES, IPSUM QUIS ULTRICIES LOBORTIS,'),
    (68, 'TURPIS TELLUS TRISTIQUE FELIS, QUIS ORNARE LACUS TELLUS EGET LEO.'),
    (69, 'IN VOLUTPAT MI VITAE PULVINAR SAGITTIS.'),
    (70, 'IN HAC HABITASSE PLATEA DICTUMST.'),
    (71, 'SED FRINGILLA, ANTE SIT AMET FAUCIBUS FINIBUS, TORTOR ORCI SODALES METUS,'),
    (72, 'QUIS VIVERRA LACUS TELLUS ID TURPIS. NULLAM HENDRERIT LOBORTIS TINCIDUNT.'),
    (73, 'PRAESENT SCELERISQUE TELLUS SIT AMET MAGNA INTERDUM, EGET CONSECTETUR SAPIEN PORTA.'),
    (74, 'CRAS PORTTITOR EGESTAS IPSUM NON MATTIS. NAM VITAE DOLOR HENDRERIT,'),
    (75, 'CURSUS FELIS VITAE, LACINIA IPSUM.'),
    (76, 'VESTIBULUM ANTE IPSUM PRIMIS IN FAUCIBUS ORCI LUCTUS ET ULTRICES POSUERE CUBILIA CURAE;'),
    (77, 'LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT.'),
    (78, 'DUIS FINIBUS TURPIS URNA, NON AUCTOR DIAM TEMPOR AT.'),
    (79, 'MAECENAS AC ELEIFEND LEO, VEHICULA TINCIDUNT AUGUE.'),
    (80, 'AENEAN VULPUTATE CONSECTETUR MASSA IN EGESTAS.'),
    (81, 'ETIAM COMMODO ORCI QUIS MOLLIS TRISTIQUE.'),
    (82, 'DUIS IN LACINIA NULLA. INTEGER SED ELEIFEND TURPIS.'),
    (83, 'DONEC UT PELLENTESQUE ENIM. ALIQUAM ERAT VOLUTPAT.'),
    (84, 'MAECENAS NEC MAXIMUS TELLUS, ID VULPUTATE MASSA.'),
    (85, 'NUNC IMPERDIET DOLOR VITAE LUCTUS CONSECTETUR.'),
    (86, 'NULLAM ID MASSA BIBENDUM, ULTRICIES DIAM ET, RHONCUS AUGUE.'),
    (87, 'MAURIS LOREM URNA, DAPIBUS UT FELIS ID, DICTUM EGESTAS MASSA.'),
    (88, 'MAURIS PLACERAT NEC IPSUM NON FAUCIBUS.'),
    (89, 'MAURIS FEUGIAT SAPIEN NON FELIS EGESTAS TEMPUS.'),
    (90, 'IN VEL RHONCUS NISI. NUNC SODALES, IPSUM QUIS ULTRICIES LOBORTIS,'),
    (91, 'TURPIS TELLUS TRISTIQUE FELIS, QUIS ORNARE LACUS TELLUS EGET LEO.'),
    (92, 'IN VOLUTPAT MI VITAE PULVINAR SAGITTIS.'),
    (93, 'IN HAC HABITASSE PLATEA DICTUMST.'),
    (94, 'SED FRINGILLA, ANTE SIT AMET FAUCIBUS FINIBUS, TORTOR ORCI SODALES METUS,'),
    (95, 'QUIS VIVERRA LACUS TELLUS ID TURPIS. NULLAM HENDRERIT LOBORTIS TINCIDUNT.'),
    (96, 'PRAESENT SCELERISQUE TELLUS SIT AMET MAGNA INTERDUM, EGET CONSECTETUR SAPIEN PORTA.'),
    (97, 'CRAS PORTTITOR EGESTAS IPSUM NON MATTIS. NAM VITAE DOLOR HENDRERIT,'),
    (98, 'CURSUS FELIS VITAE, LACINIA IPSUM.'),
    (99, 'VESTIBULUM ANTE IPSUM PRIMIS IN FAUCIBUS ORCI LUCTUS ET ULTRICES POSUERE CUBILIA CURAE;'),
    (100, 'IN VOLUTPAT MI VITAE PULVINAR SAGITTIS.');

INSERT INTO TB_DEPOIMENTO VALUES
    (1, 2, 'EU ESTAVA VOANDO DEPOIS DE TER PEGO O BUQUÊ. REALMENTE ESTOU PERPLEXO UMA MULHER TÃO PODEROSA COMO ELA, QUE ESTRANHO!! ENFIM, NÃO SEI MUITA COISA, MAS VI...  MUITO ATORMENTADO, ELE PARECE TER VISTO ALGO...'),
    (2, 3, 'EU NÃO VI NADA, EU JURO!!! EU SÓ ESTAVA INDO DAR UMA CAMINHADA QUANDO ESCUTEI ALGO ATRÁS DO MATO. COMO SOU CURIOSO FUI DAR UMA OLHADINHA. PARECIA A EMBAIXADORA GRITANDO COM UM MACHO COMO SE TIVESSE COM MEDO. ELA DIZIA PARA SE AFASTAR, MAS EU NÃO ESCUTEI MAIS NINGUÉM... ENTÃO OUVI UM RUGIDO E UM GRITO DISTANCAINDO. FOI AI QUE SAÍ CORRENDO'),
    (3, 14, 'NÃO VI MUITA COISA. MAS SE BEM QUE VI... FERDINANDO GONZÁLEZ, PASSANDO RÁPIDO POR LÁ, MEIA HORA ANTES DO QUE VOCÊ ESTÁ DIZENDO TER SIDO A HORA DO ASSASSINATO. MAS FOI RÁPIDO MESMO, NÃO DARIA TEMPO NEM DE CONVERSAR'),
    (4, 4, 'PELA COBRA NORATO, O QUE TÁ ACONTECENDO? QUEM É VOCÊ? NÃO POR FAVOR, NÃO ME MACHUQUE!!!! SOCORRO... NÃO ME MATE MONSTRO. ALGUÉM ME SALVAAAAAAA  | DICA: 24'),
    (5, 11, 'EU ESTAVA VASCULHO A ÁREA E ENCONTREI ESSA CARTA. PARECE SER UMA CARTA DE AMOR... E PARECE QUE TEM UMA SIGLA DO NOMEM DO SEU AMANTE: "F.G". E TAMBÉM TEM ESSE LÍRIO ESTRANHO JUNTO, BEM CHEIROSO POR SINAL...  ...ARGHH...  ...ARRRGH... AN? QUE? NÃO!!! POR FAVOR SE AFASTEM!!! NÃO ME MATEM SEUS MONSTROS. NÃOOOOOOO!! (ELE NO SURTO ESCORREGA E BATE A CABEÇA, COM ISSO VEM A FALECER)  | DICA: 40'),
    (6, 1, 'EU NÃO SEI O QUE HOUVE. EM UM MINUTO ELA TÁ AQUI SENDO GROSSA E RANZINZA... E DO NADA... PUFF.   ISSO DEVE SER ALGO RELACIONADO A POLITICA. FIQUEI SABENDO QUE ELA TINHA RICHA COM...');


##___________________________________________________________________________________________________________
## 							 INSERT LIXO
DELIMITER //

#DROP FUNCTION IF EXISTS GERAR_CPF;
CREATE FUNCTION GERAR_CPF() RETURNS CHAR(11)  READS SQL DATA
BEGIN
	DECLARE CPF CHAR(11);
	DECLARE DIGITOS_VERIFICADORES CHAR(2);
	DECLARE SOMA_DIGITOS1 INT;
	DECLARE SOMA_DIGITOS2 INT;
	DECLARE DIGITO_VERIFICADOR1 INT;
	DECLARE DIGITO_VERIFICADOR2 INT;

	-- GERA 9 DÍGITOS ALEATÓRIOS PARA O CPF
	SET CPF = '';
	SET @I = 1;

	WHILE @I <= 9 DO
    	SET CPF = CONCAT(CPF, FLOOR(RAND() * 9));
    	SET @I = @I + 1;
	END WHILE;

	-- CALCULA OS DÍGITOS VERIFICADORES
	SET SOMA_DIGITOS1 = (
    	SELECT
        	(SUBSTRING(CPF, 1, 1) * 10) +
        	(SUBSTRING(CPF, 2, 1) * 9) +
        	(SUBSTRING(CPF, 3, 1) * 8) +
        	(SUBSTRING(CPF, 4, 1) * 7) +
        	(SUBSTRING(CPF, 5, 1) * 6) +
        	(SUBSTRING(CPF, 6, 1) * 5) +
        	(SUBSTRING(CPF, 7, 1) * 4) +
        	(SUBSTRING(CPF, 8, 1) * 3) +
        	(SUBSTRING(CPF, 9, 1) * 2)
	) % 11;

	IF SOMA_DIGITOS1 < 2 THEN
    	SET DIGITO_VERIFICADOR1 = 0;
	ELSE
    	SET DIGITO_VERIFICADOR1 = 11 - SOMA_DIGITOS1;
	END IF;

	SET SOMA_DIGITOS2 = (
    	SELECT
        	(SUBSTRING(CPF, 1, 1) * 11) +
        	(SUBSTRING(CPF, 2, 1) * 10) +
        	(SUBSTRING(CPF, 3, 1) * 9) +
        	(SUBSTRING(CPF, 4, 1) * 8) +
        	(SUBSTRING(CPF, 5, 1) * 7) +
        	(SUBSTRING(CPF, 6, 1) * 6) +
        	(SUBSTRING(CPF, 7, 1) * 5) +
        	(SUBSTRING(CPF, 8, 1) * 4) +
        	(SUBSTRING(CPF, 9, 1) * 3) +
        	(DIGITO_VERIFICADOR1 * 2)
	) % 11;

	IF SOMA_DIGITOS2 < 2 THEN
    	SET DIGITO_VERIFICADOR2 = 0;
	ELSE
    	SET DIGITO_VERIFICADOR2 = 11 - SOMA_DIGITOS2;
	END IF;
 
	SET CPF = CONCAT(CPF, CAST(DIGITO_VERIFICADOR1 AS CHAR), CAST(DIGITO_VERIFICADOR2 AS CHAR));
    
	RETURN CPF;
END;

// DELIMITER ;


DELIMITER //
#DROP FUNCTION IF EXISTS ESCOLHER_NOME;
CREATE FUNCTION ESCOLHER_NOME()
RETURNS VARCHAR(255) DETERMINISTIC
BEGIN
	DECLARE INDICE INT;
	DECLARE NOME VARCHAR(255);
	DECLARE NOMES_ARRAY TEXT;
    
	-- DEFINIR O ARRAY DE NOMES
	SET NOMES_ARRAY = '[
	"JOÃO SILVA",
	"MARIA SANTOS",
	"PEDRO ALMEIDA",
	"ANA OLIVEIRA",
	"LUIZA FERNANDES",
	"CARLOS LIMA",
	"JULIANA PEREIRA",
	"RAFAEL SOUSA",
	"GABRIELA COSTA",
	"LUCAS GONÇALVES",
	"LAURA RODRIGUES",
	"FERNANDO CARDOSO",
	"MARIANA MENDES",
	"GUSTAVO CASTRO",
	"CAMILA CARVALHO",
	"RICARDO SANTOS",
	"ISABELA FERNANDES",
	"DIEGO OLIVEIRA",
	"BIANCA PEREIRA",
	"EDUARDO ALVES",
	"AMANDA RIBEIRO",
	"ANTÔNIO RODRIGUES",
	"CAROLINA LIMA",
	"MARCELO CASTRO",
	"HELENA CARVALHO",
	"RODRIGO SOUSA",
	"LETÍCIA COSTA",
	"JOSÉ GONÇALVES",
	"FERNANDA RODRIGUES",
	"MARCOS SANTOS",
	"LARISSA OLIVEIRA",
	"SÉRGIO PEREIRA",
	"PATRÍCIA ALMEIDA",
	"ROBERTO CARDOSO",
	"NATÁLIA MENDES",
	"ANDRÉ CASTRO",
	"VITÓRIA CARVALHO",
	"FÁBIO ALVES",
	"JÚLIA RIBEIRO",
	"RENATO RODRIGUES",
	"BRUNA LIMA",
	"PAULO CASTRO",
	"TATIANA CARVALHO",
	"CRISTIANO SOUSA",
	"VANESSA COSTA",
	"HUGO GONÇALVES",
	"LORENA RODRIGUES",
	"GERALDO SANTOS",
	"PRISCILA OLIVEIRA",
	"ALEXANDRE PEREIRA",
	"FÁTIMA RIBEIRO",
	"WAGNER CARVALHO",
	"MARIANA ALVES",
	"ROBERTO RODRIGUES",
	"CARLA LIMA",
	"DANIEL CASTRO",
	"CLÁUDIA CARVALHO",
	"SANDRO SOUSA",
	"SILVANA COSTA",
	"RAFAEL GONÇALVES",
	"DANIELA RODRIGUES",
	"HENRIQUE SANTOS",
	"TALITA OLIVEIRA",
	"RODRIGO PEREIRA",
	"BÁRBARA ALMEIDA",
	"LUCIANO CARDOSO",
	"CINTIA MENDES",
	"GUILHERME CASTRO",
	"NATALIA CARVALHO",
	"RAUL ALVES",
	"SABRINA RIBEIRO",
	"ANDRÉ RODRIGUES",
	"CRISTINA LIMA",
	"LEANDRO CASTRO",
	"MICHELE CARVALHO",
	"MARCELO SOUSA",
	"ALINE COSTA",
	"BRUNO GONÇALVES",
	"MÁRCIA RODRIGUES",
	"VITOR SANTOS",
	"CAMILA OLIVEIRA",
	"FELIPE PEREIRA",
	"LÍVIA ALMEIDA",
	"RICARDO RODRIGUES",
	"ANA LIMA",
	"RENAN CASTRO",
	"FERNANDA CARVALHO",
	"RAFAEL SOUSA",
	"LETÍCIA COSTA",
	"JOSÉ GONÇALVES",
	"FERNANDA RODRIGUES",
	"MARCOS SANTOS",
	"LARISSA OLIVEIRA",
	"SÉRGIO PEREIRA",
	"PATRÍCIA ALMEIDA",
	"ROBERTO CARDOSO",
	"NATÁLIA MENDES",
	"ANDRÉ CASTRO",
	"VITÓRIA CARVALHO",
	"FÁBIO ALVES",
	"JÚLIA RIBEIRO",
	"RENATO RODRIGUES",
	"BRUNA LIMA",
	"PAULO CASTRO",
	"TATIANA CARVALHO",
	"CRISTIANO SOUSA",
	"VANESSA COSTA",
	"HUGO GONÇALVES",
	"LORENA RODRIGUES",
	"GERALDO SANTOS",
	"PRISCILA OLIVEIRA",
	"ALEXANDRE PEREIRA",
	"FÁTIMA RIBEIRO",
	"WAGNER CARVALHO",
	"MARIANA ALVES",
	"ROBERTO RODRIGUES",
	"CARLA LIMA",
	"DANIEL CASTRO",
	"CLÁUDIA CARVALHO",
	"SANDRO SOUSA",
	"SILVANA COSTA",
	"RAFAEL GONÇALVES",
	"DANIELA RODRIGUES",
	"HENRIQUE SANTOS",
	"TALITA OLIVEIRA",
	"RODRIGO PEREIRA",
	"BÁRBARA ALMEIDA",
	"LUCIANO CARDOSO",
	"CINTIA MENDES",
	"GUILHERME CASTRO",
	"NATALIA CARVALHO",
	"RAUL ALVES",
	"SABRINA RIBEIRO",
	"ANDRÉ RODRIGUES",
	"CRISTINA LIMA",
	"LEANDRO CASTRO",
	"MICHELE CARVALHO",
	"MARCELO SOUSA",
	"ALINE COSTA",
	"BRUNO GONÇALVES",
	"MÁRCIA RODRIGUES",
	"VITOR SANTOS",
	"CAMILA OLIVEIRA",
	"FELIPE PEREIRA",
	"LÍVIA ALMEIDA",
	"RICARDO RODRIGUES",
	"ANA LIMA",
	"RENAN CASTRO",
	"FERNANDA CARVALHO"
]';
    
	-- GERAR UM ÍNDICE ALEATÓRIO
	SET INDICE = FLOOR(RAND() * 100) + 1;
    
	-- OBTER O NOME CORRESPONDENTE AO ÍNDICE
	SET NOME = JSON_EXTRACT(NOMES_ARRAY, CONCAT('$[', INDICE - 1, ']'));
    
	RETURN NOME;
END //

DELIMITER ;

DELIMITER $$
#DROP PROCEDURE IF EXISTS INSERTPERSONAGEM;
CREATE PROCEDURE INSERTPERSONAGEM()
BEGIN
  DECLARE I INT DEFAULT 15;
  WHILE I <= 85 DO
	INSERT INTO TB_PERSONAGEM VALUES (I, ESCOLHER_NOME(), GERAR_CPF() , DATE_ADD('1950-01-01', INTERVAL FLOOR( (DATEDIFF('2004-12-31', '1950-01-01') + 1) * RAND() ) DAY), FLOOR(RAND()*7 + 1), FLOOR(RAND()*39 + 1), FLOOR(RAND()*10 + 1), FLOOR(RAND()*9 + 1), FLOOR(RAND()*5 + 1), FLOOR(RAND()*4 + 1));
	SET I = I + 1;
  END WHILE;
END;


CALL INSERTPERSONAGEM();

SELECT * FROM TB_PERSONAGEM;
