#				        CRIAR BANCO DE DADOS

DROP DATABASE SQL_MYSTERY;
CREATE DATABASE SQL_MYSTERY;
USE SQL_MYSTERY;

#_____________________________________________________
#                 	TABLESPACE

DROP TABLESPACE PONTUACAO_TS; 
CREATE TABLESPACE PONTUACAO_TS 
ADD DATAFILE 'pontuacao.ibd' 
ENGINE = InnoDB;

#_____________________________________________________
#			      TABELAS DO JOGO SQL MYSTERY

#TABELA DE USUÁRIOS
CREATE TABLE TB_USUARIO (
    ID_USUARIO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(255),
	SENHA VARCHAR(255),
	EMAIL VARCHAR (255)
) TABLESPACE PONTUACAO_TS;

#TABELA DE MISTÉRIOS
CREATE TABLE TB_MISTERIO (
	ID_MISTERIO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	TITULO_MISTERIO VARCHAR(255)
) TABLESPACE PONTUACAO_TS;

#TABELA DE PONTUAÇÃO DOS USUÁRIOS
CREATE TABLE TB_PONTUACAO (
	ID_PONTUACAO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ID_MISTERIO INT UNSIGNED NOT NULL,
	ID_USUARIO INT UNSIGNED NOT NULL,
	PONTUACAO INT,
	FOREIGN KEY (ID_MISTERIO) REFERENCES TB_MISTERIO(ID_MISTERIO),
	FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)

) TABLESPACE PONTUACAO_TS;


#CONVIDADOS DO CASAMENTO
CREATE TABLE TB_PERFIL (
  ID_PERFIL INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME_PERFIL VARCHAR(255)
) COMMENT "Os tipos de perfis que um personagem pode ter";

#TABELA DAS ESPECIES DOS PERSOONAGENS DO JOGO 
CREATE TABLE TB_ESPECIE (
	ID_ESPECIE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME_ESPECIE VARCHAR(255) NOT NULL
) COMMENT "As espécies dos personagens";

#TABELA DAS MAGIAS DO REINO
CREATE TABLE TB_MAGIA (
	ID_MAGIA INT  UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    TIPO_MAGIA VARCHAR(255)
) COMMENT "Os tipos de magia dos personagens";

#TABELA DOS TITULOS DE NOBRESA 
CREATE TABLE TB_TITULO (
	ID_TITULO INT  UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    TIPO_TITULO VARCHAR(255)
) COMMENT "Os títulos que um personagem pode ter";

CREATE TABLE TB_REGIAO (
  ID_REGIAO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOME_REGIAO VARCHAR(255)
) COMMENT "As regiões onde os personagens moram";

CREATE TABLE TB_AFILIACAO (
  ID_AFILIACAO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  AFILIACAO VARCHAR(255) NOT NULL
) COMMENT "Tipos de afiliações dos personagens";

#CARTÓRIO DO MUNDO ANIMAL
CREATE TABLE TB_PERSONAGEM (
  ID_PERSONAGEM INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME_PERSONAGEM VARCHAR(255) NOT NULL,
  CAF VARCHAR(255) NOT NULL UNIQUE, #CAF (COMPROVANTE DE ANIMAL FISICO)
  DATA_NASCIMENTO DATE NOT NULL,
  ID_AFILIACAO INT UNSIGNED NOT NULL,
  ID_ESPECIE INT  UNSIGNED NOT NULL,
  ID_TITULO INT  UNSIGNED  NOT NULL,
  ID_MAGIA INT  UNSIGNED  NOT NULL,
  ID_REGIAO INT  UNSIGNED  NOT NULL,
  ID_PERFIL INT  UNSIGNED  NOT NULL,
  FOREIGN KEY (ID_PERFIL) REFERENCES TB_PERFIL(ID_PERFIL),
  FOREIGN KEY (ID_ESPECIE) REFERENCES TB_ESPECIE(ID_ESPECIE),
  FOREIGN KEY (ID_MAGIA) REFERENCES TB_MAGIA(ID_MAGIA),
  FOREIGN KEY (ID_TITULO) REFERENCES TB_TITULO(ID_TITULO), 
  FOREIGN KEY (ID_REGIAO) REFERENCES TB_REGIAO(ID_REGIAO),
  FOREIGN KEY (ID_AFILIACAO) REFERENCES TB_AFILIACAO(ID_AFILIACAO)
) COMMENT "Características do personagem";

#TABELA COM AS SALAS DOS EVENTOS
CREATE TABLE TB_SALA (
  ID_SALA INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME_SALA VARCHAR(255) NOT NULL,
  CAPACIDADE INT NOT NULL
) COMMENT "As salas do castelo";

#TABELA ITENS
CREATE TABLE TB_ITEM (
	ID_ITEM INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOME_ITEM VARCHAR(255) NOT NULL,
	ID_SALA INT UNSIGNED NOT NULL,
	CONSTRAINT ID_SALA_ITENS_FK FOREIGN KEY (ID_SALA) REFERENCES TB_SALA(ID_SALA)
) COMMENT "Os itens achados nas salas do castelo";

#TABELA  TESTEMUNHAS
CREATE TABLE TB_DEPOIMENTO (
  ID_DEPOIMENTO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ID_PERSONAGEM INT UNSIGNED NOT NULL,
  DEPOIMENTO TEXT NOT NULL,
  CONSTRAINT ID_PERSONAGEM_TESTEMUNHAS_FK FOREIGN KEY (ID_PERSONAGEM) REFERENCES TB_PERSONAGEM(ID_PERSONAGEM)
) COMMENT "Os depoimentos dados pelos personagens";

#TABELA DE SOLUÇÃO PARA VALIDAR O SUSPEITO
CREATE TABLE TB_SOLUCAO (
  ID_SOLUCAO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ID_CULPADO INT UNSIGNED NOT NULL UNIQUE,
  FOREIGN KEY (ID_CULPADO) REFERENCES TB_PERSONAGEM(ID_PERSONAGEM)
) COMMENT "O assassino";

#SEGREDO PARA AUXILIAR NA SOLUÇÃO
CREATE TABLE TB_COFRE(
  ID_COFRE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  SENHA INT NOT NULL,
  PISTA TEXT
) COMMENT "Pistas para auxiliar na investigação";

# Tabela crimes normalização da tabela ficha criminal
CREATE TABLE TB_CRIME(
	ID_CRIME INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOME_CRIME VARCHAR(100)
) COMMENT "Tipos de crimes cometidos pelos personagens";

#FICHAS CRIMINAIS DO REINO
CREATE TABLE TB_FICHA_CRIMINAL(
  ID_FICHA_CRIMINAL INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ID_PERSONAGEM INT UNSIGNED NOT NULL,
  INICIO_PENA DATE NOT NULL,
  FIM_PENA DATE NOT NULL,
  ID_CRIME INT UNSIGNED,
  STATUS ENUM('PRESO','LIVRE') NOT NULL,
  CONSTRAINT ID_PERSONAGEM_CRIME_FK FOREIGN KEY (ID_PERSONAGEM) REFERENCES TB_PERSONAGEM(ID_PERSONAGEM),
  FOREIGN KEY (ID_CRIME) REFERENCES TB_CRIME(ID_CRIME)
) COMMENT "Fichas criminais dos personagens";

#CARACTERISTICAS DA PELE
CREATE TABLE TB_PELE (
  ID_PELE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  PELE VARCHAR(255) NOT NULL
) COMMENT "Cor do pelo ou pele dos personagens";

#CARACTERISTICAS FISICAS DOS PERSONAGENS
CREATE TABLE TB_MORFOLOGIA(
  ID_APARENCIA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ID_PERSONAGEM INT UNSIGNED NOT NULL UNIQUE,
  ID_PELE INT UNSIGNED NOT NULL,
  OLHOS VARCHAR(255) NOT NULL,
  ALTURA FLOAT NOT NULL,
  CONSTRAINT ID_PERSONAGEM_MORFOLOGIA_FK FOREIGN KEY (ID_PERSONAGEM) REFERENCES TB_PERSONAGEM(ID_PERSONAGEM),
  CONSTRAINT ID_PELE_MORFOLOGIA_FK FOREIGN KEY (ID_PELE) REFERENCES TB_PELE(ID_PELE)
 ) COMMENT "Aparência dos personagens";

#DICAS DO PERSONAGEM SECUNDARIO 
CREATE TABLE TB_DICA (
  ID_DICA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  DICA TEXT NOT NULL
) COMMENT "Dicas que o personagem secundário pode falar";

#TABELA DO EVENTO DO CASAMENTO 
CREATE TABLE TB_EVENTO (
	ID_EVENTO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOME_EVENTO VARCHAR(255) NOT NULL
) COMMENT "Eventos que aconteceram";

#PROGRAMAÇÕES DO EVENTO
CREATE TABLE TB_PROGRAMACAO (
  ID_PROGRAMACAO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOME_PROGRAMACAO VARCHAR(255) NOT NULL,
  ID_SALA INT UNSIGNED NOT NULL, 
  ID_EVENTO INT UNSIGNED NOT NULL,
  HORA_INICIO TIME NOT NULL,
  HORA_FINAL TIME NOT NULL,
  FOREIGN KEY (ID_SALA) REFERENCES TB_SALA(ID_SALA),
  FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO(ID_EVENTO)
) COMMENT "As partes dos eventos";

CREATE TABLE TB_CONVITE (
	ID_CONVITE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ID_EVENTO INT UNSIGNED NOT NULL,
  ID_PERSONAGEM INT UNSIGNED NOT NULL,
  CONFIRMACAO BOOL,
  FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO(ID_EVENTO),
  FOREIGN KEY (ID_PERSONAGEM) REFERENCES TB_PERSONAGEM(ID_PERSONAGEM)
) COMMENT "Confirmação dos convidados para os eventos";

CREATE TABLE TB_FUNCAO (
	ID_FUNCAO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  NOME_FUNCAO VARCHAR(255)
) COMMENT "Funções exercidas pelos funcionários";

CREATE TABLE TB_CONTRATO (
	ID_CONTRATO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_EVENTO INT UNSIGNED NOT NULL,
    ID_PERSONAGEM INT UNSIGNED NOT NULL,
    ID_FUNCAO INT UNSIGNED NOT NULL,
    FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO(ID_EVENTO),
    FOREIGN KEY (ID_PERSONAGEM) REFERENCES TB_PERSONAGEM(ID_PERSONAGEM),
    FOREIGN KEY (ID_FUNCAO) REFERENCES TB_FUNCAO(ID_FUNCAO)
) COMMENT "Contratos entre os eventos e os funcionários";
